aphdstreaming/livestream/urls.py
from django.conf.urls import url

from . import views

app_name = 'livestream'

urlpatterns = [
    url(
        regex=r'^$',
        view=views.Index,
        name='index'
    ),

    url(
        regex=r'^event/(?P<id>[0-9]+)/',
        view=views.Event_Stream,
        name='Event'
    ),

    url(
    	regex=r'^liveevent/add/$',
    	view =views.Event_Add,
    	name='Live_Event_Add'
    ),

]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("aphdstreaming.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("livestream/", include('aphdstreaming.livestream.urls', namespace='livestream')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

aphdstreaming/livestream/models.py
from django.db import models
from aphdstreaming.core.models import BaseEntity
from django.core.validators import RegexValidator

import random
import string
# Create your models here.

def stream_directory_path(event, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'stream_{0}/{1}'.format(event.Stream_Key, filename)

def images_stream_directory_path(image, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'stream_{0}/{1}'.format(image.event.Stream_Key, filename)

def randomString(len = 12):
    """Generate a random string of letters, digits and special characters """

    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(20))

class Event(BaseEntity):
    """ Event is a single live stream that can
        can be carried out"""
    STATUS_CHOICES=(
        ('CREATED', 'created'),
        ('CONFIRMED', 'Confirmed'),
        ('INPROGRESS', 'Inprogress'),
        ('COMPLETED', 'Completed')
    )

    Bride = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='name should contain only alphabets',
				code='invalid_name'
			),
		]
	)
    Groom = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='name should contain only alphabets',
				code='invalid_name'
			),
		]
	)
    Message = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='message should contain only alphabets',
				code='invalid_name'
			),
		]
	)
    time = models.DateTimeField(
        verbose_name='Event Time',
        )
    status = models.CharField(
        max_length =15,
        choices = STATUS_CHOICES,
        default = 'CREATED',
    )
    Bride_Img = models.ImageField(
        upload_to=stream_directory_path,
        blank=True,
        null=True,
        )
    Groom_Img = models.ImageField(
        upload_to=stream_directory_path,
        blank=True,
        null=True,
        )
    Poster_Img = models.ImageField(
        upload_to=stream_directory_path,
        blank=True,
        null=True,
        )
    Studio = models.CharField(
		max_length=80,
	)
    Stream_Key = models.CharField(
		max_length=80,
        editable = False,
	)
    start_date_time = models.DateTimeField(
        verbose_name='Start Date Time',
        )

    end_date_time = models.DateTimeField(
        verbose_name='End Date Time',
        )
    studio_person = models.CharField(
		max_length=80,
        blank =True,
        null = True,
	)
    studio_phone = models.CharField(
		max_length=13,
        blank = True,
        null = True,
		validators=[
        RegexValidator(
            regex='^[0-9]{10}$',
            message='Phone number should contain only 10 numbers',
			code='invalid Phone number'
			),
    	]
	)
    studio_email = models.EmailField(
        max_length = 254,
        blank = True,
        null = True
    )



    def save(self, *args, **kwargs):
        if not self.Stream_Key:
            self.Stream_Key = randomString()
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        bride = self.Bride.replace(" ", "")
        groom = self.Groom.replace(" ", "")
        msg = self.Message.replace(" ", "")
        return bride+msg+groom


class Image(BaseEntity):
    """Images for Carousel of an event """
    event = models.ForeignKey(
        Event,
        related_name='images',
        on_delete=models.CASCADE
    )

    photo = models.ImageField(
        upload_to=images_stream_directory_path,
        blank=True,
        null=True,
        )

aphdstreaming/livestream/forms.py
from django import forms

from crispy_forms.helper import FormHelper

from .models import  Event
from .widgets import XDSoftDateTimePickerInput


class DateInput(forms.DateInput):
	input_type = 'date'

class EventForm(forms.ModelForm):
	"""form for Event"""
	time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput())
	start_date_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput())
	end_date_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput())

	helper = FormHelper()
	helper.form_tag = False
	helper.form_style = 'inline'

	class Meta:
		model = Event
		exclude = ['']

aphdstreaming/livestream/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from django.db.models import  Q



from .models import Event
from .forms import EventForm

#Base_HLS_URL = 'http://live.balajidigitals.in:8080/live/'
#Base_RTMP_URL = 'rtmp://stream.balajidigitals.in/live/'
Base_INTENT = "intent://stream.balajidigitals.in/live/"

Base_HLS_URL = 'http://localhost:8080/live/'
Base_RTMP_URL = 'rtmp://127.0.0.1/live/'
# Create your views here.
@login_required
def Index(request):
    events = Event.objects.filter(~Q(status='COMPLETED'))
    return render(request, 'index.html',{'events': events})

def Event_Stream(request, id):
    event= get_object_or_404(Event, pk=id)
    current_time = timezone.localtime(timezone.now())
    if event.end_date_time <= current_time:
        ext = '.mp4'
    else:
        ext = '.m3u8'
    hlsurl = Base_HLS_URL +event.Stream_Key + '/' +event.Stream_Key + ext
    rtmpurl = Base_RTMP_URL + event.Stream_Key
    intenturl = Base_INTENT + event.Stream_Key + '/' +event.Stream_Key + ext
    if event.start_date_time <= current_time :
        return render(request, 'event.html', {'event': event, 'hlsurl': hlsurl , 'rtmpurl': rtmpurl, 'intenturl' : intenturl})
    else:
        return HttpResponse("<h1>Invalid Stream</h1>")

@login_required
#@user_passes_test(Permission_Check,redirect_field_name= None)
def Event_Add(request):
    files = request.FILES
    for f in files:
        print("printing file : ")
        print(f)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save()
            return HttpResponseRedirect(reverse('livestream:index'))
    else:
        form = EventForm()
    return render(request, 'live_event_add.html',{'form':form})

aphdstreaming/livestream/templates/event.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{event.Studio}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="{% static 'jw.js' %}"></script>

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

<body height: 100%;>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-header bg-primary">
            <h3 class="display-4 text-center">{{event.Studio}} </h1>
          </div>
          <div class="card-body">

            <div class="row text-center">
              <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card">
                    <img class="card-img-top" src="{{ MEDIA_URL }}/{{event.Bride_Img}}" alt="">
                    <div class="card-body">
                      <h4 class="card-title">{{event.Bride}}</h4>
                    </div>
                  </div>
                </div>

              <div class="col-lg-4 col-md-6 mb-4 align-self-center">
                  <div class="card border-0">
                    <img class="card-img-top rounded-circle" src="{% static 'images/weds.jpeg' %}" alt="">
                    <div class="card-body">
                      <h4 class="card-title">{{ event.Message }}</h4>
                      <p class="card-text">{{event.time}}</p>
                    </div>
                  </div>
                </div>

              <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card">
                    <div id="logo"><img class="card-img-top img-responsive" src="{{ MEDIA_URL }}/{{event.Groom_Img}}" alt=""></div>
                    <div class="card-body">
                      <h4 class="card-title">{{event.Groom}}</h4>
                    </div>
                  </div>
                </div>

            </div>
        {% if event.images.all %}
          <div id="demo" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ul class="carousel-indicators">
              <li data-target="#demo" data-slide-to="0" class="active"></li>
              {% for i in event.images.all %}
              <li data-target="#demo" data-slide-to="{{forloop.counter}}"></li>
              {% endfor %}
            </ul>

            <!-- The slideshow -->
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{ MEDIA_URL }}/{{event.Poster_Img}}" alt="" class="img-fluid" >
              </div>
              {% for i in event.images.all %}
              <div class="carousel-item">
                <img src="{{ MEDIA_URL }}/{{i.photo}}" alt="" class="img-fluid">
              </div>
              {% endfor %}
            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
              <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
              <span class="carousel-control-next-icon"></span>
            </a>
          </div>
        {% endif %}
          <br><br>
        <div class="row align-items-center justify-content-center">
          <div id='player' width=960 height=400 >

          </div>
	  <h3>
            <a href="{{intenturl}}#Intent;action=android.intent.action.VIEW;scheme=https;type=application/x-mpegURL;end">Click here to Play the video in your favorite app</a>
          </h3>
        </div>
        </div>
      </div>
      <div class="text-center bg-primary">
        <footer>
        <h1>{{event.Studio}}</h1>
	{% if event.studio_person %}
        <h1>{{event.studio_person}}</h1>
        <h2>{{event.studio_phone}}</h2>
        {% if event.studio_email %}
          <h3> {{event.studio_email}}</h3>
        {% endif %}
	{% endif %}
      </footer>
      </div>

    </div>
  </div>
</div>


  {% block javascript %}
    <!-- Required by Bootstrap v4 Alpha 4 -->
    <script src="https://use.fontawesome.com/640bd40708.js"></script>
<!--      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->



    <script>
    $('.carousel').carousel();
    jwplayer('player').setup ({
      file: '{{hlsurl}}',
      image: '{{ MEDIA_URL }}/{{event.Poster_Img}}',
      title:"{{event.Bride}}  {{event.Message}}  {{event.Groom}} ",
      description: "Live Streaming",
      controls: 'true',
      "sharing": {
        "sites": ["facebook","twitter", "reddit"]
      }
  });


    </script>




    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


  {% endblock javascript %}
</body>
</html>

aphdstreaming/livestream/templates/event2.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Live Stream

{% endblock %}

{% block additionalcss %}
<link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">


{% endblock %}

{% block content %}



<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header bg-primary">
        <h3 class="display-5 text-center">{{event.Studio}} Presents</h1>
      </div>
      <div class="card-body">

        <div class="row text-center">

          <div class="col-lg-4 col-md-6 mb-4">
              <div class="card">
                <img class="card-img-top" src="/media/{{event.Bride_Img}}" alt="">
                <div class="card-body">
                  <h4 class="card-title">{{event.Bride}}</h4>
                  <p class="card-text">Bride Description</p>
                </div>
              </div>
            </div>

          <div class="col-lg-4 col-md-6 mb-4 align-self-center">
              <div class="card border-0">
                <img class="card-img-top rounded-circle" src="{% static 'images/weds.jpeg' %}" alt="">
                <div class="card-body">
                  <h4 class="card-title">Time</h4>
                  <p class="card-text">09/07/2019 05:09:10</p>
                </div>
              </div>
            </div>

          <div class="col-lg-4 col-md-6 mb-4">
              <div class="card">
                <div id="logo"><img class="card-img-top img-responsive" src="/media/{{event.Groom_Img}}" alt=""></div>
                <div class="card-body">
                  <h4 class="card-title">{{event.Groom}}</h4>
                  <p class="card-text">Groom description</p>
                </div>
              </div>
            </div>

        </div>
        <div class="row align-items-center justify-content-center">
          <video id=example-video width=960 height=400 class="video-js vjs-default-skin " controls>
            <source
              src="{{ srcurl }}"
              type="application/x-mpegURL">
          </video>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock content %}


{% block additionaljs %}

<script src="https://unpkg.com/video.js/dist/video.js"></script>
<script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>
<script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>

<script>
  (function(window, videojs) {
    var player = window.player = videojs('example-video');

  }(window, window.videojs));
</script>

{% endblock %}
















<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <meta charset="utf-8">
  <meta http-equiv="Cache-Control" content="private, no-store, max-age=0, no-cache, must-revalidate, post-check=0, pre-check=0"/>
  <meta http-equiv="Pragma" content="no-cache"/>
  <meta http-equiv="Expires" content="0"/>

  <title>Video Plugin Scoping Issue</title>

  <link href="http://vjs.zencdn.net/5.0/video-js.css" rel="stylesheet">
  <link href="../node_modules/videojs-annotations/lib/videojs-annotations.css" rel="stylesheet">

  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
    }
    .video-js, .embed {
      display: block;
      margin: 40px auto;
    }
  </style>
</head>
<body>
  <h2>Player</h2>

  <video id="video"
         class="video-js vjs-big-play-centered"
         height="300"
         width="600"
         poster="test/poster.jpg"
         controls
  >
    <p>
      Your browser doesn't support video. Please <a href="http://browsehappy.com/">upgrade your browser</a> to see the example.
    </p>
  </video>

  <h2>Secondary</h2>

  <video id="video-secondary"
         class="video-js vjs-big-play-centered"
         height="300"
         width="600"
         poster="test/poster.jpg"
         controls
  >
    <p>
      Your browser doesn't support video. Please <a href="http://browsehappy.com/">upgrade your browser</a> to see the example.
    </p>
  </video>

  <script src='../node_modules/video.js/dist/video.js'></script>
  <script src='../node_modules/videojs-resolution-switcher/lib/videojs-resolution-switcher.js'></script>
  <script src='../node_modules/videojs-annotations/lib/videojs-annotations.js'></script>

  <script>
    // safari fix, force webkit to reload if page is loaded from back button
    window.onpageshow = function(e) {
      if (e.persisted) {
        window.location.reload();
      }
    };

    var player1 = videojs('video', {
      plugins: {
        videoJsResolutionSwitcher: {
          default: 'low',
          dynamicLabel: true
        },

        annotations: {
          annotations: [
            {start: 3, end: 6, top: '30%', left: '30%', width: '10%', height: '10%', text: 'first', url: 'http://www.somethingawful.com'},
            {start: 5, end: 10, top: '50%', left: '50%', width: '30%', height: '30%', text: 'second', url: 'http://www.twitter.com', imageUrl: 'http://lorempixel.com/400/200/sports/2/'}
          ]
        }
      }
    }, function() {
      console.log('player 1 ready', this);
      this.updateSrc([
        {
          src: 'test/placeholder480p.mp4',
          type: 'video/mp4',
          label: 'SD',
          res: 360
        },
        {
          src: 'test/placeholder1080p.mp4',
          type: 'video/mp4',
          label: 'HD',
          res: 720
        }
      ]);
    });

    var player2 = videojs('video-secondary', {
      plugins: {
        videoJsResolutionSwitcher: {
          default: 'low',
          dynamicLabel: true
        },

        annotations: {
          annotations: [
            {start: 3, end: 6, top: '30%', left: '30%', width: '10%', height: '10%', text: 'first', url: 'http://www.somethingawful.com'},
            {start: 5, end: 10, top: '50%', left: '50%', width: '30%', height: '30%', text: 'second', url: 'http://www.twitter.com', imageUrl: 'http://lorempixel.com/400/200/sports/2/'}
          ]
        }
      }
    }, function() {
      console.log('player 2 ready', this);
      this.updateSrc([
        {
          src: 'test/placeholder480p.mp4',
          type: 'video/mp4',
          label: 'SD',
          res: 360
        },
        {
          src: 'test/placeholder1080p.mp4',
          type: 'video/mp4',
          label: 'HD',
          res: 720
        }
      ]);
    });
  </script>
</body>
</html>

aphdstreaming/livestream/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Live Stream

{% endblock %}



{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>list of events</h2>
      <br/>
      <a href="{% url 'livestream:Live_Event_Add' %}"><button type="button" class="btn btn-primary">Add Event</button></a>
      <hr/>
  <div class="table-responsive">
     <table id="eventsTable" class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Bride</th>
          <th>Groom</th>
          <th>Start Date</th>
          <th>Stream key</th>
          <th>Link</th>

        </tr>
      </thead>
      <tbody>
      {% for e in events %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ e.Bride }}</td>
          <td>{{ e.Groom }}</td>
          <td>{{ e.start_date_time }}</td>
          <td>{{ e.Stream_Key }}</td>
          <td><a href="{% url 'livestream:Event' e.id %}">https://aphdstreaming.in{% url 'livestream:Event' e.id %}{{e}}</a></td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
    </div>
  </div>





</div>
{% endblock content %}

{% block additionaljs %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script type="text/javascript">
$(document).ready( function () {
    $('#eventsTable').dataTable( {
  "pageLength": 50
} );
} );
</script>

{% endblock %}

aphdstreaming/livestream/templates/jwplayer.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>JW player</title>
    <script src="{% static 'jw.js' %}"></script>
  </head>
  <body>
  <div id="jw">

  </div>
  <script type="text/javascript">
   function autorun()
   {
     jwplayer('jw').setup ({
       file: '{{hlsurl}}'
   });
   }
   if (window.addEventListener) window.addEventListener("load", autorun, false);
   else if (window.attachEvent) window.attachEvent("onload", autorun);
   else window.onload = autorun;
  </script>
  </body>
</html>

aphdstreaming/livestream/templates/live_event_add.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Add Live Event

{% endblock %}
{% block additionalcss %}

<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="{% static 'datetimepicker-2.5.20/jquery.datetimepicker.min.css' %}">

{% endblock %}
{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Add Live Event</h2>
     <form action="." method="POST" enctype="multipart/form-data" autocomplete="off" >
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Submit" class="btn btn-primary">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>

    </div>
  </div>


</div>
{% endblock content %}

{% block additionaljs %}
<script src="{% static 'datetimepicker-2.5.20/jquery.datetimepicker.full.min.js' %}"></script>
{% endblock %}